version: '1'
context:
  active-host: 'hy027.us1.dbt.com'
  active-project: '70471823406816'
projects:
  - project-name: 'Analytics'
    project-id: '70471823406816'
    account-name: 'explorer'
    account-id: '70471823405433'
    account-host: 'hy027.us1.dbt.com'
    token-name: 'cloud-cli-2027'
    token-value: { { tocken_value } }

model-paths: ['models']
analysis-paths: ['analyses']
test-paths: ['tests']
seed-paths: ['seeds']
macro-paths: ['macros']
snapshot-paths: ['snapshots']

target-path: 'target'
clean-targets:
  - 'target'
  - 'dbt_packages'

vars:
  truncate_timespan_to: '{{ current_timestamp() }}'

models:
  core_platform:
    staging:
      +materialized: view
    marts:
      +materialized: table
